services:
  users:
    build: ./api-users
    ports:
      - "3001:3001"
    links:
      - postgres-database
    environment:
      - PORT=3001
      - JWT_SECRET=SUPER_SECRET_KEY
      - FRONTEND_URL=https://localhost:3003
      - DATABASE_URL=postgresql://postgres:root@postgres-database:5432/docker_users?schema=public
  products:
    build: ./api-products
    ports:
      - "3002:3002"
    links:
      - postgres-database
    environment:
      - PORT=3002
      - FRONTEND_URL=https://localhost:3003
      - DATABASE_URL=postgresql://postgres:root@postgres-database:5432/docker_products?schema=public
  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    links:
      - users
      - products
    environment:
      - PORT=3000
      - JWT_SECRET=SUPER_SECRET_KEY
      - FRONTEND_URL=https://localhost:3003
  postgres-database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-database:/var/lib/postgresql/data

volumes:
  postgres-database:
